"use strict";
var a;
var b;
var c;
var d;
var e;
a = 34.34, e = 34;
b = 'Welcome To TypeScript';
c = true;
d = { id: '100', name: 'sanjay' };
var arrowFn = function (a, e) { return a + e; };
arrowFn(a, e);
var arr;
arr = [1, 2, 3, 4, 5];
var diffArray;
diffArray = [1, true, 'Sanjay'];
var add = function (a, b) {
    return a + b;
};
console.log(add(3, 9));
